[package]
name = "kafka_producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.34", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
